version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - pragmatic_class_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - pragmatic_class_static:/data/static/
      - pragmatic_class_media:/data/media/
      - gis_log:/var/log/nginx/

  django:
    image: pragmatic_class:5
    networks:
      - pragmatic_class_network
    volumes:
      - pragmatic_class_static:/home/WebApplicationClass/staticfiles/
      - pragmatic_class_media:/home/WebApplicationClass/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - pragmatic_class_network
    volumes:
      - pragmatic_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  pragmatic_class_network:

volumes:
  pragmatic_class_static:
  pragmatic_class_media:
  pragmatic_mariadb:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true